services:
  - name: selenium-cron-job
    type: worker
    env: python
    plan: free
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: "/usr/bin/google-chrome"
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"
